using UnityEngine;
using UnityEngine.Audio;
using UnityEngine.SceneManagement;

public class AudioManager : MonoBehaviour
{
    public static AudioManager Instance;

    public AudioSource bgmSource;
    //public AudioSource sfxSource;

    public AudioClip homeBGM;
    public AudioClip gameBGM;
    public AudioClip resultBGM;

    void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
            SceneManager.sceneLoaded += OnSceneLoaded;
        }
        else
        {
            Destroy(gameObject);
        }
    }

    private void Update()
    {
        if (!bgmSource.isPlaying)
        {
            Debug.LogWarning("BGMが再生されていません");
        }

    }

    void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        PlayBGMForScene(scene.name);
    }

    void PlayBGMForScene(string sceneName)
    {
        AudioClip clip = null;
        switch (sceneName)
        {
            case "HomeScene": clip = homeBGM; break;
            case "GameScene": clip = gameBGM; break;
            case "ResultScene": clip = resultBGM; break;
        }

        if (clip != null && bgmSource.clip != clip)
        {
            bgmSource.clip = clip;
            bgmSource.loop = true;
            bgmSource.Play();
        }
    }

    public void PlaySFX(AudioClip clip)
    {
        if (clip == null) return;

        // 一時的なAudioSource付きGameObjectを生成
        GameObject tempGO = new GameObject("sfxAudio");
        AudioSource aSource = tempGO.AddComponent<AudioSource>();
        aSource.clip = clip;
        //aSource内設定追加はここ

        aSource.Play();

        // 再生終了後に自動で削除
        Destroy(tempGO, clip.length);
    }
}
