using UnityEngine;

public class WallsManager : MonoBehaviour
{
    private float destroyZ = -5f;

    private BackgroundsManager backgroundsManager;

    [System.Obsolete]
    private void Start()
    {
        // シーン上に1つだけあるBackgroundsManagerを検索
        backgroundsManager = FindObjectOfType<BackgroundsManager>();
        if (backgroundsManager == null)
        {
            Debug.LogError("BackgroundsManagerが見つかりません。");
        }
    }

    void Update()
    {
        if (backgroundsManager == null) return;

        float currentSpeed = backgroundsManager.speed;
        transform.Translate(0, 0, -currentSpeed * Time.deltaTime, Space.World);

        if (transform.position.z < destroyZ)
        {
            Destroy(gameObject);
        }
    }
}
